name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Using YOUR forked checkout action
      - name: Checkout repository
        uses: Gaurav-singh101/checkout@main
        
      # Using YOUR forked snake action
      - name: Generate snake.svg
        uses: Gaurav-singh101/snk@main
        with:
          github_user_name: Gaurav-singh101
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
          
      # Using YOUR forked github pages action
      - name: Deploy to GitHub Pages
        uses: Gaurav-singh101/ghaction-github-pages@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
